include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.gen.dart
    - lib/**.mocks.dart
    - lib/generated/**
    - test/**.mocks.dart

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true